### ISSUE TITLE
Some problems have been encountered in using TDEseq

### ISSUE THREAD

**Issue by Chamberlain1993** [fanyue322/TDEseq#4]
Your method is very good, I would like to use. My single-cell data consisted of five time points, each of which I extracted a sample to run the analysis, and I extracted only the epithelial cells in the sample for analysis. Is that possible? Does your method work for only one type of cell, rather than all annotated cells? I think my data volume is not very big, but it has been running for more than 2 days, is this normal? In addition, I have a question is, according to the method you provide with heat map visualization, the heat map of the data is based on what? Did you just draw the genes with P < 0.05? This visualization, when I'm doing it, I can't see the time points on the graph? How does this add up? If there are any other visual methods recommended, thank you very much.
!
[1720605966492](https://github.com/fanyue322/TDEseq/assets/129367051/a59395ae-fd7f-4707-9210-9f96701d8004)

**Comment by fanyue322** [comment]
Hi Chamberlain1993,

I apologize for the delayed reply.

Regarding your first question, TDEseq is specifically designed for the analysis of a single cell type, rather than analysis of all cells. 

As for your second question, could you please clarify the mode you are utilizing with TDEseq? If you have been employing the Linear Mixed Model (LMM) version, you might consider switching to the Linear Model (LM) version, which offers significantly enhanced speed. Alternatively, the pseudocell mode could be a viable option.

In response to your third question, the heatmap is generated utilizing the top 50 genes from each identified pattern—Growth, Recession, Peak, and Trough. This feature is primarily intended for a rapid visualization of the results. For creating figures intended for publication, I would recommend leveraging the capabilities of the ComplexHeatmap package, which provides more sophisticated visualization options.

Best regards
